### PR TITLE
Revised website from GAP Days Spring 2024

### LINKED ISSUE #70: GAP Authors
http://www.gap-system.org/Contacts/People/authors.html says:

"For all authors the contributions can be identified from the header of the library or kernel files. If you want to find the contributions of a particular author you should grep the library and kernel files searching for the full name (first name and family name but no title) of the respective author"

- is this still true? Some files may have names, but this does not seem to be the rule still followed any more.

Also, while GAP revisions history prior to the move to GitHub contains generic `gap` commits, we can mention that in addition to this list, contributors after the move to GitHub may be seen from the revisions history.

### LINKED ISSUE #163: Unify "Releases" / "Downloads" pages in Jekyll
Compare e.g. these:
- https://www.gap-system.org/Releases/4.11.0.html
- https://www.gap-system.org/Releases/4.7.5.html
- https://www.gap-system.org/Releases/4.6.3.html

They look quite a bit different. 

On the other hand, the following two are very similar; but most of that similar content is created via "code duplication":
- https://www.gap-system.org/Releases/4.11.0.html
- https://www.gap-system.org/Releases/4.10.2.html

I would like to factor out more of the comment content, so that it doesn't have to repeated via copy&paste, and so that improvements also benefit older versions. But care has to be taken, in particular, watch out for these special cases with multiple package lists (we might want to split these packages into 2 resp. 3):
- https://www.gap-system.org/Releases/4.5.4.html
- https://www.gap-system.org/Releases/4.5.6.html

One idea for that: add `_includes/release_list_downloads.html` with a single argument, a list of file "records". Then render a table as shown on the most recent release pages (or perhaps improve on that "layout"). Then adapt all releases to use that include file; put the file lists into their front matter YAML.

For the remaining duplication, we have to be careful because not all releases have the same set of files, so we can't put it all in a single template. But we could have additional include files to help with that.

### LINKED ISSUE #341: Change `package_status` to treat unlisted packages as "deposited" instead of erroring out

### PR DESCRIPTION
**Pull request by fingolfin**
With lots of contributions by @schnellecom @ruthhoffmann @MeikeWeiss 

Major changes:
- new responsive layout (so the page also works great on mobile and tablets)
- unified the various install/download/release/... pages
- new site structure, making it hopefully easier to find content
- removed a lot of content, because it was outdated or of limited usefulness or just plain off-topic (this makes it easier for us to maintain the site; but also in some cases all that content made it harder to find the things that actually matter)
- ...

Resolves #341
Resolves #163
Resolves #70

TODO:
- [x] Get rid of placeholder index.html files as much as possible..
      From `git grep -l "Empty document to protect directory"` we find:
     - [x] About/Capabilities/index.html
     - [x] About/History/index.html
     - [ ] Doc/Bib/MSC/index.html
     - [ ] Doc/Bib/Year/index.html
     - [x] Doc/Bib/index.html
     - [x] Doc/Learning/index.html
     - [x] Doc/Teaching/index.html
     - [x] Doc/index.html
     - [x] Faq/index.html
     - [x] Packages/Authors/index.html
     - [x] Packages/index.html
- [x] Get rid of the last traces of `_Releases` section
- [x] clean up the FAQ, delete many obsolete or trivial questions
- [ ] ensure all pages have consistently styled permalinks
- [x] update to GAP 4.13.0
- [x] check all pages for broken links (e.g. using [lychee](https://lychee.cli.rs), fix broken links 
     - [ ] the FAQ and `Doc/Learning/learning.html` have multiple links to things under `Doc/Talks/` and `Doc/Examples/` (which we deleted... maybe some should be restored?)
     - [x] many links to `/Gap3/` pages can be found under `About/Capabilities`
     - [x] two links to `Doc/references.html` under `About/Capabilities` (perhaps should be kept? seems somewhat useful...)
     - [x] `Doc/Bib/statistics.html`
     - [x] `Doc/Bib/Year/year.html`
     - [x] `Doc/Bib/MSC/msc.html`
- [x] there is substantial overlap in content between the pages `/Install/`, `/Install/release.html`, and the sub-pages for macos/linux/windows installation -- we should resolve that, probably by merging `/Install/release.html` into the other pages suitably
- [x] find remaining links to package pages, e.g. just noticed `<a href="../Packages/scscp.html">SCSCP package</a>` in the FAQ
- [ ] convert more .html files to .md
- [x] decide if we want to use consistently lower case URL styles (so e.g. `/install` instead of `/Install`) which seems to be the norm these days
- [x] setup redirects for at least some of the old URLs to the new ones
- [ ] Max: analyze the server log files to see if we can figure out which are the most "popular" pages; and which pages are being linked to from outside (if the logs allow that, don't know)
- [ ] final cleanup before merging:
    - [ ] either delete `.github/workflows/jekyll.yml` or adjust it for `master`
    - [ ] revert `dev` branch specific changes in `webhook.php` and `etc/` (we probably should keep them on dev, though -- hmmm, need to think about how to pull that off)

### CODE REVIEW

**Comment by fingolfin** [comment]
Some things to be done:
- [ ] The Linux install page could point to repology (taking the link in the FAQ and probably removing it there
- [ ] rename https://dev.gap-system.org/Download/ to https://dev.gap-system.org/install or https://dev.gap-system.org/Install or so?
- [ ] set up a bunch of redirects for certain old URLs???
- [ ] ...

**Comment by ruthhoffmann** [comment]
`core.html ` is now `default_with_header.html`

**Comment by fingolfin** [comment]
More things I noticed:
- "Overview" is an odd name for a top-level nav item. Gotta think about that one
- "Overview" 95% is about capabilities -- and then it also has "History", that's odd, I wouldn't find "History" there. Move History (back) to "DOcumentation"? Or add a new top level section "Miscellaneous"?
- also "Funding" is under "History" which makes no sense to me -- well I do see how it might fit as "history of Funding", but this is more about giving credit, so it fits better with things like copyright / license / citing ... Maybe a common top level category for that, such as "Credits" or so...?
- Get rid of placeholder `index.html` files as much as possible. Starting point:
```
git grep -l "Empty document to protect directory"
Contacts/Council/index.md
Contacts/Forum/index.md
Contacts/index.md
Doc/Bib/MSC/index.html
Doc/Bib/Year/index.html
Doc/Bib/index.html
Doc/Learning/index.html
Doc/Teaching/index.html
Doc/index.html
Faq/index.html
Overview/Capabilities/index.html
Overview/History/index.html
Overview/index.html
Packages/Authors/index.html
Packages/index.html
```

**Comment by fingolfin** [comment]
Broken package links: the various release pages such as https://dev.gap-system.org/Releases/4.12.2.html contain a list of packages included in that release. These tables are sometimes useful to determine which version of a package was shipped in a certain GAP release...

... but they all now have broken links of the form <https://dev.gap-system.org/Packages/ace.html> but @MeikeWeiss removed those pages because we said we don't need them anymore thank to @schnellecom work on the new package list...

Possible fixes that come to mind:
1. reintroduce those packages pages -- I'd really rather not do that...
2. remove those lists -- they are not useful for most people. Though they sometimes *are* useful to e.g. me ... :-)
3. replace them with additional instances of the package list table @schnellecom created
   - this would require a tweak to `loadPackageTable.js` which currently hardcodes `latest.json` as source; instead it should get the filename as a "parameter" somehow
   - I think we can probably do that by first having a tiny snippet of inline JavaScript which sets a global variable to the filename, and then use that global variable in `loadPackageTable.js`
   - bonus: this would also allow us to get rid of `latest.json` again

**Comment by fingolfin** [comment]
`Overview/Capabilities/groups.html` still references `Datalib/datalib.html` which is gone

**Comment by fingolfin** [comment]
Another solution to the package lists on the various "Releases" pages: just get rid of those pages. Instead, open up access to https://files.gap-system.org/ (i.e., show the directory listings) so anyone who really wants those files can "click through" to them.

**Comment by fingolfin** [comment]
@schnellecom I wonder why the first column in the packages table is so wide, see screenshot. Tested in Safari, Firefox, Vivaldi (which is based on Chrome).

Screen Shot 2024-03-18 at 17 28 03

**Comment by fingolfin** [comment]
We will have to update `dev/releases/update_website.py` in https://github.com/gap-system/gap in several ways:

- it scans the removed directory `_Releases` to determine what the latest GAP release is. But we can just read `_data/release.json` for that instead?
  - note the the script currently distinguish between `known_release` and `newest_release` so it can in theory add releases that are not the "latest" (say if we wanted to make a GAP 4.12.3 release today). This is not really necessary to support. So the code can be simplified in this regard.

- it creates a file `_Releases/{version}.html` like `_Releases/4.13.1.html` -- I think this can just be deleted.

- `_data/package-infos/{version_safe}.json` now is `assets/package-infos.json`

- `_Packages/` is gone



I think we can actually considerably simplify `update_website.py` if instead of grabbing a list of *all* releases known to GitHub, we only ask for the release that is marked as "latest". And then possibly check whether it is greater than the release currently in the website (not sure we really need to do that, though)

**Comment by ruthhoffmann** [comment]
Hurray! 🎉 Well done everyone!

**Pull request merged**
