### PR TITLE
rm Packages/pkgstaticlist

### PR DESCRIPTION
**Pull request by ssiccha**
This file is unused. It may have been used to create the data in
/Packages/pkgconf.py.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@ssiccha this file is actually used - you can perhaps see in its history that it was updated every release. It is autogenerated and then used for the long list of packages included in the given GAP release. So yeah, there is no need to keep it under version control in principle...

**Comment by ssiccha** [comment]
@alex-konovalov Do you know which file generates it? Is this a file from the gap-distribution repo? I've grepped in GapWWW for the filename `pkgstaticlist` and didn't find any mentions.

>  It is autogenerated and then used for the long list of packages included in the given GAP release. 

So the content is copied manually into e.g. `_Releases/4.11.0.html`? In this case it would be nice if there were a file with instructions how to generate e.g. `_Releases/4.11.0.html` that explicitly states to "then copy the content from `Packages/pkgstaticlist`". That would make it more discoverable where this file comes from and what it is used for.

**Comment by alex-konovalov** [comment]
Yes, generated in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/PackageInfoTools.g

**Comment by alex-konovalov** [comment]
@ssiccha you can see which files are generated by that file in this commit: https://github.com/gap-system/GapWWW/commit/cfbfd20e87ab9e340fe2fffdee475db32f17f9bb

**Comment by ssiccha** [comment]
Awesome, good to know! Many thanks. So as per the discussion on jitsi and slack in the future we're gonna make a script in the GapWWW repo to generate all the files in https://github.com/gap-system/GapWWW/commit/cfbfd20e87ab9e340fe2fffdee475db32f17f9bb .

**Pull request merged**
