### PR TITLE
Improve the bibitem sorting in convbib.g

### PR DESCRIPTION
**Pull request by fingolfin**
Previously we just sorted by author name; now we also use the title of a publication
as a tie breaker if two papers have the exact same author string

Moreover, convert all strings used for sorting from Unicode to lowercase ASCII and
remove some special characters, to further reduce strangeness in the sorting result.
It's still not perfect, but a lot better than what was in place before.

Finally, we use a stable sort to get rid of any random fluctuations that might be
left in the sorting process (there shouldn't be any, but better stay on the safe side).

Also rerun convbib.g afterwards.

Once a new GAPDoc release is out, we should also re-run this, as it includes various enhancements (e.g. right now, there several entries for Ákos Seress which just list him as "Seress" because the LaTeX sequence `\'{A}` is not handled by GAPDoc <= 1.6.3. (see also https://github.com/frankluebeck/GAPDoc/issues/42 for another related issue).

### CODE REVIEW

**Comment by frankluebeck** [comment]
This change looks fine and sensible to me. 

I'm only wondering if the title is a good second key for the sorting.  Isn't usually the publication year used as second key in bibliographies? (Then the title could still be used as third key.)

**Comment by fingolfin** [comment]
Agreed, the year is a better second sorting key. Will change it, and re-run with the latest GAPDoc

**Comment by fingolfin** [comment]
I updated this PR to sort by authors, then year, then title. Also, the last commit re-runs `convbib.g` with the latest GAPDoc so that the changes it causes are easy to review. I did so and they are a clear improvement without any regressions that I could spot.

**Comment by fingolfin** [comment]
To quote myself :-)
> Also, the last commit re-runs convbib.g with the latest GAPDoc

**Comment by alex-konovalov** [comment]
@fingolfin the word "latest" could mean, to quote myself :)

> latest released GAPDoc or latest GAPDoc from its repository

so I can't parse the text "with the latest GAPDoc" without a requested clarification.

**Comment by alex-konovalov** [comment]
I have now 88 potential GAP citations, will have another test of this soon...

**Pull request merged**
