### PR TITLE
Fix link to GAP package dependency graph

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
The working link is https://alexk.host.cs.st-andrews.ac.uk/gap/GAP_Packages.html

**Comment by fingolfin** [comment]
@alex-konovalov not sure what to make of that. Do you mean you prefer to fix the link? If so, of course that's also fine by me, then we can close this PR.

**Comment by alex-konovalov** [comment]
@fingolfin I have updated the dependencies graph. Please update the link and I will merge this PR.

GAP_Packages1_1

**Comment by fingolfin** [comment]
PR updated as requested

**Comment by flyingapfopenguin** [comment]
The link seems to work and the graph looks plausible to me, but @alex-konovalov should approve that.

**Comment by alex-konovalov** [comment]
Merged - will appear after next update (this is not a live repo - I need to update its clone on the web server)

**Pull request merged**
