### PR TITLE
Conversion of Faq from Mixer to Jekyll

### PR DESCRIPTION
**Pull request by User141**
We changed every line with mixer and introduced a namelink feature for persons.

### CODE REVIEW

**Comment by fingolfin** [comment]
Easiest way to rebase is to use an interactive rebase onto the current `jekyll` branch: Enter this command for that:  `git rebase -i origin/jekyll`. This will open an editor with three lines for three commits (plus a bunch of comment lines). Remove the first commit, i.e., `pick 048de54 Start work on Jekyll conversion`. Save & close the file -- git should complete the rebase instantly. Now you can push your changes (requires adding the `-f` option to do a force push, as you rewrote history and git/GitHub want to protect you from making a mistake).

**Comment by User141** [comment]
I have only one commit:

pick a5f4a94 preparation for rebase

# Rebase 53b2f4e..a5f4a94 onto 53b2f4e (1 command)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

**Comment by fingolfin** [comment]
@User141 well in my instructions I assumed that `origin` refers to `gap-system` -- but maybe that's not true for you. You clearly have an outdated copy of the `jekyll` branch around somewhere. And also this PR was not created on its own branch, adding to the confusion...

So, first make sure you have a git remote that refers to `gap-system` -- check via `git remove -v`. If you have none, you can add one, e.g.
```
git remote add gap-system https://github.com/gap-system/GapWWW
git fetch gap-system
git rebase -i gap-system/jekyll
```

**Comment by User141** [comment]
Ok, thanks. This time it worked i think.

**Comment by fingolfin** [comment]
Could you explain the "preparation for rebase" commit?

**Pull request merged**
