### PR TITLE
rm Datalib/irreduc.html

### PR DESCRIPTION
**Pull request by ssiccha**
This file is not linked from the Datalib/datalib.html site. It contains
information about a primitive solvable groups library, which was
superseded by the PrimGrp library package.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin @ssiccha even if the file is not linked, does not mean that it's not referenced from elsewhere. I think that's the reason why this page is still there. It's plausible that such links exist, although I did not find them. What I have found so far is 

- https://mail.gap-system.org/pipermail/forum/2016.txt -> http://www.gap-system.org/Datalib/imf.html
- https://mail.gap-system.org/pipermail/forum/2014.txt -> http://www.gap-system.org/Datalib/trans.html
- Galois Theory By Ian Nicholas Stewart -> http://www.gap-system.org/Datalib/trans.html 
- https://people.clas.ufl.edu/sin/files/a5stab.pdf -> http://www.gap- system.org/Datalib/prim.html
- https://www.sciencedirect.com/science/article/pii/S0021869308000653/ -> http://www.gap-system.org/Datalib/tom.html

**Comment by fingolfin** [comment]
If such links exist, I think it's good that we'll break them with the switch to Jekyll. That page is a zombie page, and any people looking at it are being mislead about the true state of things.

**Comment by alex-konovalov** [comment]
@fingolfin what was misleading in saying this?
```
  Irreducible solvable subgroups of GL(n,q) for q<sup>n</sup> up	
  to 243, calculated by M. Short, are now included in the	
  <a href="/Packages/primgrp.html">PrimGrp</a> package.
```
The package acknowledges M.Short's data at https://www.gap-system.org/Manuals/pkg/primgrp-3.4.0/doc/chap1.html.

**Comment by fingolfin** [comment]
It's misleading to have this isolated page which is not reachable via normal means. It either should be integrated into the navigation, or removed. As it is, the contributions by M. Short are already acknowledge in the PrimGrp manual, and also on <https://www.gap-system.org/Datalib/datalib.html>. So I see no value in keeping that page.

**Pull request merged**
