### PR TITLE
cleanup lib/config, remove unused stuff

### PR DESCRIPTION
**Pull request by fingolfin**
Also merge GAPKernelVersion and GAPLibraryVersion

### CODE REVIEW

**Comment by fingolfin** [comment]
@alex-konovalov does this seem OK to you?

**Comment by alex-konovalov** [comment]
@fingolfin first, this should be rebased. Second, instead of using both formats like `gap45ftp` and `gap47www`, perhaps we should rename gap45ftp to gap45www and change its url to https://www.gap-system.org/pub/gap/gap45/. Then when we will rebuild e.g. https://www.gap-system.org/Releases/4.5.5.html links will offer https downloads. At the moment, they offer ftp download which asks for authorisation.

**Comment by fingolfin** [comment]
@alex-konovalov done, and also added `gap44www` to unbreak GAP 4.4.12 downloads.

**Comment by fingolfin** [comment]
actually, I should also take care of gapftpdir and a few comments. Will update again ASAP

**Comment by fingolfin** [comment]
@alex-konovalov updated again

**Comment by fingolfin** [comment]
@alex-konovalov I restored this PR to its old version, i.e., the former first commit; this way, it should be easy to review, yet is sufficient to unbreak https://github.com/gap-system/gap-distribution/pull/95

**Pull request merged**
