### PR TITLE
Change <mixer var="GAP"/> to just GAP, remove several unused Mixer variables

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
I verified that this PR does not change the generated HTML (by diffing before/after). I am going to merge it now, as it is the one thing that makes PR #121 "big"

**Comment by alex-konovalov** [comment]
Fine. Will not go live till the end of next week, but will open you the way for next changes.

**Comment by fingolfin** [comment]
No need for this to be online, just in the repo helps :-)

**Comment by alex-konovalov** [comment]
Fine. I think initial plan was that `GAP` should be rendered differently, but trying to adhere to this rule is difficult and inconvenient, and with markdown will be even more problematic. So I welcome this change.

**Pull request merged**
