### PR TITLE
Added Gabor Horvath to authors list.

### PR DESCRIPTION
**Pull request by Stefan-Kohl**
Added Gabor Horvath to authors list.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@Stefan-Kohl Thank you for this PR. 

Just to note that it's related to PR #4 and it's actually not necessary actually to submit it as a separate PR - the best practice here is to put things that are related together in the same pull request which may unite several commits. However, from the name of the branch `patch-2` it looks like you edited the file and submitted PR via the web-interface. In this case, it may be indeed non-trivial to submit more complicated PR involving several changes in several files (I've never tried!), so I am happy to make an exception and merge several pull requests for THIS project - but please note that for code repositories that will be not considered a suitable practice and we will advise to make a proper clone of the repository on your machine and work from there.

Next, this PR is incomplete, since `<li> <mixer person="Gabor Horvath" data="name_link_city"/> </li>` needs data from `lib/addresses` file to resolve `data="name_link_city"`. Please see how @fingolfin added new persons at https://github.com/gap-system/GapWWW/pull/3/files and add an entry to `lib/addresses` by analogy.

**Comment by Stefan-Kohl** [comment]
Why shouldn't one use the web interface if github provides it? -- I think using the web interface is
the most convenient way to make occasional changes. Of course if one makes lots of commits,
one may prefer another interface.

**Comment by fingolfin** [comment]
I don't see a major problem with using the GitHub interface to make minor changes. But if a change (as in this case) requires editing three or more files at once, it is a bit annoying to get three pull requests. The resulting history is uglier, and the three pull requests cannot properly tested, as they are interdependant.

It is, however, possible to use the GitHub webinterface to make a pull request with multiple commits in it. It is not completely trivial, though:

1. Make the first edit as before
2. Once that is done and saved, switch to the new branch this created in your fork of the project. E.g. I just made one here: https://github.com/fingolfin/GapWWW/tree/fingolfin-patch-1
3. Next, edit the second file -- but edit it *here*, i.e. in your fork, not in the original repository. Before pressing the "Commit changes" button, make sure your changes are added to the existing branch, not into a separate one -- for this example, I thus made sure that the radio button "Commit directly to the fingolfin-patch-1 branch " was selected (that was the default anyway)
4. Done. You can add more commits like that. Once you are finished, you can open the pull request by browsing to the front page of the GapWWW repository (doesn't matter whether it is the original or your fork), and GitHub wil helpfull suggest that you may want to merge your work. This leads to a page like this one https://github.com/gap-system/GapWWW/compare/master...fingolfin:fingolfin-patch-1?expand=1

**Comment by frankluebeck** [comment]
While the encoding changes were indeed all wrong, there are a few entries close to the end of 
http://gap-system.org/Contacts/People/modules.html
which could be corrected (`"o`, `'e` and so on).

Furthermore, there must be an  entry in `lib/addresses` for the new author and maintainer.

**Comment by alex-konovalov** [comment]
After PR #9, this should now work.

**Pull request merged**
