### PR TITLE
Switch from Mixer to Jekyll

### PR DESCRIPTION
**Pull request by fingolfin**
This is work in progress (and possibly in a semi-broken state at any given time); I mainly put it here to allow people who are interested in the conversion of our website from the proprietary [Mixer](https://github.com/gap-system/Mixer) static site generator to [Jekyll](https://jekyllrb.com). Interested in both how it works, in trying it, but most importantly, in helping out with it.

Details on how this is supposed to work can be found [in this HackMD](https://hackmd.io/EUtMx_2mRTaIYYlWSaVI6A) and also in [README.jekyll.md](https://github.com/gap-system/GapWWW/blob/jekyll/README.jekyll.md)

Some tasks:
- [x] convert all `.mixer` files to Jekyll files
  - [x] adapt scripts which generate .mixer files for bibliography to generate Jekyll files instead
  - [x] adapt scripts which generate .mixer files for packages
- [x] come up with a way to produce a "nice" navigation menu (in the left sidebar) in Jekyll
- [x] rewrites script which generates `lib/AllLinksOfAllHelpSections.data` to directly produce `_data/help.yml` instead (right now `etc/sync_mixer_to_jekyll.py` converts the former to the latter)
- ...

### CODE REVIEW

**Comment by Stefan-Kohl** [comment]
@fingolfin Does this change affect the redirect from http://www.gap-system.org/DevelopersPages/StefanKohl/ to https://stefan-kohl.github.io/ in any way?

**Comment by fingolfin** [comment]
@Stefan-Kohl no. That redirect is implemented in the config file of the webserver anyway, not in our HTML code. What we did do however is replace several instances in the HTML of http://www.gap-system.org/DevelopersPages/StefanKohl/ by https://stefan-kohl.github.io/ to avoid the redirect there

**Comment by fingolfin** [comment]
This is done now. Thanks to all participants of the first virtual GAP Days for their contributions!

**Comment by ssiccha** [comment]
:tada:

**Pull request merged**
