### PR TITLE
Delete an outdated copy of GAP INSTALL file

### LINKED ISSUE #206: Remove https://www.gap-system.org/Download/INSTALL
It is outdated, and thus potentially dangerous.

We could either just remove it; or replace it with a page that links to the actual instructions....

See also discussion on https://github.com/gap-system/gap/pull/4168

### PR DESCRIPTION
**Pull request by alex-konovalov**
Indeed, we now link directly to the version of GAP installation
instructions tagged with the release.

Closes #206

### CODE REVIEW

**Review by fingolfin — COMMENTED** [review]
Are there any links to this file?

**Comment by alex-konovalov** [comment]
Ah yes `grep -R -w INSTALL *` returns some. Will fix.

**Comment by fingolfin** [comment]
@alex-konovalov ping?

**Comment by fingolfin** [comment]
I could not find any reference to this INSTALL, so I am merging this.

**Comment by alex-konovalov** [comment]
@fingolfin you're right - they all refer to the file from the main repository or the distribution. Thanks!

**Pull request merged**
