### PR TITLE
Turn top left "GAP" white-on-blue cell into link

### PR DESCRIPTION
**Pull request by fingolfin**
... which links to the start page of the GAP homepage. That's a
common pattern for websites.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Oops :( doesn't look as expected

screen shot 2017-09-12 at 11 00 50

**Comment by alex-konovalov** [comment]
@fingolfin this is weird. When I am building the website with Mixer locally, it looks fine - white letters on the blue background, and the word "GAP" is a hyperlink but not underlined. When I'm doing this on the host server, I see it as above.

**Comment by fingolfin** [comment]
Old CSS may still be in cache try a "force reload" (typically achieved by pressing reload in a browser plus some modifier key(s))

**Comment by alex-konovalov** [comment]
Thanks @fingolfin :)

**Pull request merged**
