### PR TITLE
Update website for GAP 4.11.1 release

### PR DESCRIPTION
**Pull request by fingolfin**
Please don't merge this hastily, I first want to deploy it to the test site

UPDATE: now deployed to https://test.gap-system.org please take a look

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin https://test.gap-system.org/Packages/packages.html lists PolymakeInterface - but changes log says "PolymakeInterface: Following the withdrawal of the package Convex in GAP 4.11.0 because of being superseded by NConvex, the PolymakeInterface has also been withdrawn. These two packages are now replaced by NormalizInterface and NConvex", so you need to remove it, and add manually the text to the bottom of that page about withdrawn packages.

**Comment by fingolfin** [comment]
@alex-konovalov done

**Review by ssiccha — APPROVED** [review]
I've had a quick look at the website and tried out a few links. Everything looked good to me, but then I have no idea how the packages section is supposed to look like.

**Review by wilfwilson — COMMENTED** [review]
It all looks as I would expect. In more details, the only problems I can see are the broken links to package documentation, package READMEs, and package archives.

e.g. https://test.gap-system.org/Packages/4ti2interface.html

**Comment by wilfwilson** [comment]
@fingolfin If you'd like, I can rebase #231 onto this branch and push it? Or we can let that be a separate, later, change (if it's going to be accepted at all).

**Comment by fingolfin** [comment]
@wilfwilson you could also push your work in #231 as an add-on to this PR, then it'll be deployed once we make the release. As you wish!

**Comment by wilfwilson** [comment]
> @you could also push your work in #231 as an add-on to this PR

Sorry, that's what I meant to propose (but is not what I said). I have done so, and I've updated <test.gap-system.org> (see e.g. https://test.gap-system.org/Packages/gapdoc.html)

**Review by alex-konovalov — APPROVED** [review]

**Review by wilfwilson — APPROVED** [review]
I think this is in a good state

**Pull request merged**
